# Generated by Django 5.0.2 on 2024-02-28 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Birinchi qatorni kiriting')),
                ('title1', models.CharField(max_length=100, verbose_name='ikkinchi qatorni kiriting')),
                ('title2', models.CharField(max_length=100, verbose_name='uchinchi qatorni kiriting')),
                ('photo', models.ImageField(upload_to='aksiya/photo', verbose_name='Aksiya uchun foto kiriting 370x240 olchamda')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand nomini kiriting')),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('photo1', models.ImageField(blank=True, default=None, null=True, upload_to='slider/photo', verbose_name='Brand logosini yuklang agar bolsa 370x240 olchamda')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Kategoriya nomini kiriting')),
                ('cat_slug', models.SlugField(max_length=10, unique=True)),
                ('cat_photo', models.ImageField(blank=True, default=None, null=True, upload_to='category/photo', verbose_name='Categoriya uchun foto 370x240 olchamda')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rang nomini kiriting')),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Size nomini kiriting')),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Birinchi qatorni kiriting')),
                ('title1', models.CharField(max_length=100, verbose_name='Ikkinchi qatorni kiriting')),
                ('title2', models.CharField(max_length=100, verbose_name='Uchinchi qatorni kiriting')),
                ('photo', models.ImageField(upload_to='slider/photo', verbose_name='Slide uchun foto kiriting 1920x753 olchamda')),
                ('photo1', models.ImageField(upload_to='slider/photo', verbose_name='Kichik banner uchun foto kiriting 1170x250 olchamda')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='product/photo', verbose_name='Tovar fotosini kiriting')),
                ('date_updated', models.DateField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, default='nomalum raqam', max_length=13, null=True)),
                ('country', models.CharField(blank=True, choices=[('UZ', "O'zbekiston"), ('KG', "Qirg'iziston"), ('KZ', "Qozog'iston"), ('TJ', 'Tojikiston'), ('TM', 'Turkmaniston'), ('AF', "Afg'oniston")], default='Noaniq davlat', max_length=100, null=True)),
                ('city', models.CharField(blank=True, choices=[('TAS', 'Toshkent shahri'), ('AND', 'Andijon viloyati'), ('NAM', 'Namangan viloyati'), ('SAM', 'Samarqand viloyati'), ('FAR', "Farg'ona viloyati"), ('SUR', 'Surxondaryo viloyati'), ('JIZ', 'Jizzax viloyati'), ('KAS', 'Qashqadaryo viloyati'), ('NAV', 'Navoiy viloyati'), ('XOR', 'Xorazm viloyati'), ('KAR', 'Karakalpakistan Respublikasi'), ('SIR', 'Sirdaryo viloyati'), ('BUK', 'Buxoro viloyati')], default='Noaniq shaxar', max_length=100, null=True)),
                ('adress', models.CharField(blank=True, default='Manzil noaniq', max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, default='Pochta noaniq', max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomini kiriting')),
                ('min_content', models.TextField(max_length=300, verbose_name='Mahsulotga qisqacha tarif')),
                ('max_content', models.TextField(max_length=1500, verbose_name='Mahsulotga batafsil tarif')),
                ('price', models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='Narxni belgilang')),
                ('articul', models.BigIntegerField(blank=True, default='', null=True)),
                ('photo1', models.ImageField(upload_to='product/photo', verbose_name='Tovar fotosini kiriting')),
                ('photo2', models.ImageField(blank=True, default=None, null=True, upload_to='product/photo', verbose_name='Tovar fotosini kiriting')),
                ('photo3', models.ImageField(blank=True, default=None, null=True, upload_to='product/photo', verbose_name='Tovar fotosini kiriting')),
                ('photo4', models.ImageField(blank=True, default=None, null=True, upload_to='product/photo', verbose_name='Tovar fotosini kiriting')),
                ('photo5', models.ImageField(blank=True, default=None, null=True, upload_to='product/photo', verbose_name='Tovar fotosini kiriting')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('sale', models.BooleanField(default=False)),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Skidka tugash sanasini belgilang')),
                ('data_sale', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=10, null=True, verbose_name='Skidka Narxni belgilang')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.brands', verbose_name='Brandni tanlang')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category', verbose_name='Kategoriyani tanlang')),
                ('colors', models.ManyToManyField(to='my_app.colors', verbose_name='Rangini tanlang')),
                ('size', models.ManyToManyField(to='my_app.size', verbose_name="O'lchamni tanlang")),
            ],
        ),
    ]
