# Generated by Django 5.0.2 on 2024-02-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Birinchi qatorni kiriting')),
                ('title1', models.CharField(max_length=100, verbose_name='ikkinchi qatorni kiriting')),
                ('title2', models.CharField(max_length=100, verbose_name='uchinchi qatorni kiriting')),
                ('photo', models.ImageField(upload_to='slider/photo', verbose_name='slide uchun foto kiriting 1920x753 olchamda')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
