# Generated by Django 5.0.2 on 2024-02-18 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_aksiya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, verbose_name='Kategoriya nomini kiriting')),
                ('cat_slug', models.SlugField(max_length=10, unique=True)),
                ('cat_photo', models.ImageField(upload_to='category/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Size nomini kiriting')),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomini kiriting')),
                ('min_content', models.TextField(max_length=100)),
                ('max_content', models.TextField(max_length=1500)),
                ('price', models.BigIntegerField(max_length=15)),
                ('articul', models.BigIntegerField(unique=True)),
                ('photo1', models.ImageField(upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda')),
                ('photo2', models.ImageField(upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda')),
                ('photo3', models.ImageField(upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda')),
                ('photo4', models.ImageField(upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda')),
                ('photo5', models.ImageField(upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category', verbose_name='kategoriyani tanlang')),
                ('size', models.ManyToManyField(to='my_app.size', verbose_name='razmerni tanlang')),
            ],
        ),
    ]
