# Generated by Django 5.0.2 on 2024-02-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_category_size_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='category/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
