# Generated by Django 5.0.2 on 2024-02-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_product_slug_alter_category_cat_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomini kiriting')),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
        ),
    ]
