# Generated by Django 5.0.2 on 2024-02-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='my_app.colors', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_content',
            field=models.TextField(max_length=300),
        ),
    ]
