# Generated by Django 5.0.2 on 2024-02-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='photo1',
            field=models.ImageField(default=1, upload_to='slider/photo', verbose_name='kichik banner uchun foto kiriting 1170x250 olchamda'),
            preserve_default=False,
        ),
    ]
