# Generated by Django 5.0.2 on 2024-02-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_slider_photo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomini kiriting')),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('photo1', models.ImageField(upload_to='slider/photo', verbose_name='slide uchun foto kiriting 370x240 olchamda')),
            ],
        ),
    ]
