# Generated by Django 5.0.2 on 2024-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_aksiya_photo_alter_category_cat_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.BigIntegerField(default=''),
        ),
    ]
