# Generated by Django 5.0.2 on 2024-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_product_articul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.BigIntegerField(blank=True, default='', null=True),
        ),
    ]
