# Generated by Django 5.0.2 on 2024-02-18 13:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_product_articul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(max_length=255, null=True, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('addres', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Brand nomini kiriting'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='photo1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='slider/photo', verbose_name='Brand logosini yuklang agar bolsa 370x240 olchamda'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Rang nomini kiriting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='my_app.colors', verbose_name='Rangini tanlang'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(upload_to='product/photo', verbose_name='Tovar fotosini kiriting'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Narxni belgilang'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(blank=True, default=',', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.product')),
            ],
        ),
    ]
