# Generated by Django 5.0.2 on 2024-02-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_client_alter_brands_name_alter_brands_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
