# Generated by Django 5.0.2 on 2024-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_product_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True, verbose_name='Skidka Narxni belgilang'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Skidka tugash sanasini belgilang'),
        ),
    ]
