# Generated by Django 5.0.2 on 2024-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_product_sale_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='Narxni belgilang'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=10, null=True, verbose_name='Skidka Narxni belgilang'),
        ),
    ]
