# Generated by Django 5.0.2 on 2024-02-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Skidka tugash sanasini belgilang'),
        ),
    ]
