# Generated by Django 5.0.2 on 2024-02-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_product_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_sale',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
