# Generated by Django 5.0.2 on 2024-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_product_data_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_sale',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
