# Generated by Django 5.0.2 on 2024-02-26 19:07

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_product_data_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=True, null=True, upload_to='profile')),
                ('date_updated', models.DateField(auto_now=True, verbose_name=django.contrib.auth.models.User)),
                ('phone_number', models.CharField(blank=True, default=True, max_length=13, null=True)),
                ('country', models.CharField(blank=True, choices=[('UZ', "O'zbekiston"), ('KG', "Qirg'iziston"), ('KZ', "Qozog'iston"), ('TJ', 'Tojikiston'), ('TM', 'Turkmaniston'), ('AF', "Afg'oniston")], default=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, choices=[('TAS', 'Toshkent shahri'), ('AND', 'Andijon viloyati'), ('NAM', 'Namangan viloyati'), ('SAM', 'Samarqand viloyati'), ('FAR', "Farg'ona viloyati"), ('SUR', 'Surxondaryo viloyati'), ('JIZ', 'Jizzax viloyati'), ('KAS', 'Qashqadaryo viloyati'), ('NAV', 'Navoiy viloyati'), ('XOR', 'Xorazm viloyati'), ('KAR', 'Karakalpakistan Respublikasi'), ('SIR', 'Sirdaryo viloyati'), ('BUK', 'Buxoro viloyati')], default=True, max_length=100, null=True)),
                ('adress', models.CharField(blank=True, default=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, default=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
