# Generated by Django 5.0.2 on 2024-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_alter_profile_adress_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/photo', verbose_name='Tovar fotosini kiriting'),
        ),
    ]
